// Learning Lions - Programming Fundamentals - Comments 2
// Author: TC
// Module: LL-PF
// Copyright: 2017 Learning Lions. CC0 - Feel free to do whatever you want.



const family_members = 5; //
var comments = ["Single Line Comments", "Multi-line Comments", "JSDoc"]; //
var dog = "dog"; //
var dogfamily = dog * family_members; //
var testdog = 5 + family_members + dog; //
var dogtest = dog + family_members + 5; //




function Goat(goatfood) {
	// Code goes here
	// and here
	// ...
}